[package]
name = "smol"
# When publishing a new version:
# - Update CHANGELOG.md
# - Create "v1.x.y" git tag
version = "1.2.5"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
rust-version = "1.46"
description = "A small and fast async runtime"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/smol-rs/smol"
homepage = "https://github.com/smol-rs/smol"
documentation = "https://docs.rs/smol"
keywords = ["async", "await", "future", "io", "networking"]
categories = ["asynchronous", "concurrency", "network-programming"]
exclude = ["/.*"]

[dependencies]
async-channel = {path="../async-channel"}
async-executor = {version="1.1.0",path = "../async-executor"}
async-fs = "1.3.0"
async-io = {version="1.1.2",path="../async-io"}
async-lock = "2.3.0"
async-net = "1.4.3"
blocking = "1.0.0"
futures-lite = "1.11.0"
once_cell = "1.4.1"
log = "0.4"

[target.'cfg(not(target_os = "espidf"))'.dependencies]
async-process = "1.0.0"

[dev-dependencies]
anyhow = "1"
async-dup = "1"
async-h1 = "2"
async-native-tls = "0.4"
async-tungstenite = { version = "0.16", features = ["async-native-tls"] }
ctrlc = "3"
doc-comment = "0.3"
futures = "0.3"
http = "0.2"
http-types = "2"
hyper = { version = "0.14", default-features = false, features = ["client", "http1", "server", "stream"] }
native-tls = "0.2"
scraper = "0.12"
signal-hook = "0.3"
surf = { version = "2", default-features = false, features = ["h1-client"] }
tempfile = "3"
tokio = { version = "1", default-features = false, features = ["rt-multi-thread"] }
tungstenite = "0.16"
url = "2"

[target.'cfg(target_os = "linux")'.dev-dependencies]
inotify = { version = "0.10", default-features = false }
nix = "0.23"
timerfd = "1"

[target.'cfg(windows)'.dev-dependencies]
uds_windows = "1"
