[package]
name = "async-io"
# When publishing a new version:
# - Update CHANGELOG.md
# - Create "v1.x.y" git tag
version = "1.6.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
rust-version = "1.46"
description = "Async I/O and timers"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/smol-rs/async-io"
homepage = "https://github.com/smol-rs/async-io"
documentation = "https://docs.rs/async-io"
keywords = ["mio", "epoll", "kqueue", "iocp", "wepoll"]
categories = ["asynchronous", "network-programming", "os"]
exclude = ["/.*"]

[dependencies]
concurrent-queue = {path="../concurrent-queue"}
futures-lite = "1.11.0"
log = "0.4.11"
once_cell = "1.4.1"
parking = {path="../parking"}
polling = {path="../polling"}
slab = "0.4.2"
socket2 = { version = "0.4.2", features = ["all"] }
waker-fn = "1.1.0"
[target."cfg(unix)".dependencies]
libc = "0.2.77"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winsock2"] }

[dev-dependencies]
async-channel = "1.4.2"
async-net = "1.3.0"
blocking = "1.0.0"
signal-hook = "0.3"
tempfile = "3.1.0"

[target.'cfg(target_os = "linux")'.dev-dependencies]
inotify = { version = "0.10", default-features = false }
nix = "0.23"
timerfd = "1.1.1"

[target.'cfg(windows)'.dev-dependencies]
uds_windows = "1"
